### PR TITLE
Add exception handling for instance ids

### PR DESCRIPTION
**Pull request by MartinYSpasov**
Add exception handling for instance ids

### CODE REVIEW

**Comment by iamrichardjones** [comment]
I like the tests. What does the class checking give us? Am I being stupid? ;)

**Comment by MartinYSpasov** [comment]
In an ideal world we (devs) want to have exceptions as descriptive as possible :). One application might have hundreds of instance ids objects and throwing an exception (with class name and value) for invalid input can save developer considerable debugging time. However I am open for suggestions  :)

**Comment by iamrichardjones** [comment]
still dont get it Im afraid  ;)

If I want to instantiate PersonId then I pass in an integer. Im probably being stupid. Can you update the tests to show what you mean? The extra tests you did are perfect. If you want them in a separate pull request I'll get those in straight away

**Comment by iamrichardjones** [comment]
merged :)
Thanks

**Pull request merged**
